{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb8cc4c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Dukalis\\AppData\\Local\\Temp\\ipykernel_4780\\1068401516.py:3: UserWarning: \n",
      "The dash_core_components package is deprecated. Please replace\n",
      "`import dash_core_components as dcc` with `from dash import dcc`\n",
      "  import dash_core_components as dcc\n",
      "C:\\Users\\Dukalis\\AppData\\Local\\Temp\\ipykernel_4780\\1068401516.py:4: UserWarning: \n",
      "The dash_html_components package is deprecated. Please replace\n",
      "`import dash_html_components as html` with `from dash import html`\n",
      "  import dash_html_components as html\n",
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:8050\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [25/May/2023 12:01:51] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_9_3m1685005281.14.0.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_9_3m1685005281.8.1.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/deps/react@16.v2_9_3m1685005281.14.0.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_9_3m1685005281.12.1.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_9_2m1685005280.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_9_3m1685005280.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_2_4m1685005280.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_11m1685005281.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_9_2m1685005281.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n",
      "[2023-05-25 12:01:52,516] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_callback.py\", line 491, in add_context\n",
      "    jsonResponse = to_json(response)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type coroutine is not JSON serializable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_callback.py\", line 493, in add_context\n",
      "    _validate.fail_callback_output(output_value, output)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 334, in fail_callback_output\n",
      "    _validate_value(val, index=i)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 324, in _validate_value\n",
      "    _raise_invalid(\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 238, in _raise_invalid\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback for `<Output `output-table.children`>`\n",
      "                returned a value having type `coroutine`\n",
      "                which is not JSON serializable.\n",
      "\n",
      "\n",
      "The value in question is either the only value returned,\n",
      "or is in the top level of the returned list,\n",
      "\n",
      "                and has string representation\n",
      "                `<coroutine object scan_devices at 0x000001C96E9EE8F0>`\n",
      "\n",
      "                In general, Dash properties can only be\n",
      "                dash components, strings, dictionaries, numbers, None,\n",
      "                or lists of those.\n",
      "127.0.0.1 - - [25/May/2023 12:01:52] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2023-05-25 12:02:04,163] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_callback.py\", line 491, in add_context\n",
      "    jsonResponse = to_json(response)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type coroutine is not JSON serializable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_callback.py\", line 493, in add_context\n",
      "    _validate.fail_callback_output(output_value, output)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 334, in fail_callback_output\n",
      "    _validate_value(val, index=i)\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 324, in _validate_value\n",
      "    _raise_invalid(\n",
      "  File \"C:\\Users\\Dukalis\\AppData\\Roaming\\Python\\Python310\\site-packages\\dash\\_validate.py\", line 238, in _raise_invalid\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback for `<Output `output-table.children`>`\n",
      "                returned a value having type `coroutine`\n",
      "                which is not JSON serializable.\n",
      "\n",
      "\n",
      "The value in question is either the only value returned,\n",
      "or is in the top level of the returned list,\n",
      "\n",
      "                and has string representation\n",
      "                `<coroutine object scan_devices at 0x000001C96EC1BF40>`\n",
      "\n",
      "                In general, Dash properties can only be\n",
      "                dash components, strings, dictionaries, numbers, None,\n",
      "                or lists of those.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\anaconda3\\lib\\site-packages\\werkzeug\\datastructures.py:1025: RuntimeWarning:\n",
      "\n",
      "coroutine 'scan_devices' was never awaited\n",
      "\n",
      "127.0.0.1 - - [25/May/2023 12:02:04] \"POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from bleak import BleakScanner\n",
    "\n",
    "app = dash.Dash(__name__)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1('Сканирование Bluetooth устройств'),\n",
    "    html.Label('Начальный номер устройства:'),\n",
    "    dcc.Input(id='start-range', type='number', value=1),\n",
    "    html.Label('Конечный номер устройства:'),\n",
    "    dcc.Input(id='end-range', type='number', value=10),\n",
    "    html.Label('Время сканирования (в секундах):'),\n",
    "    dcc.Input(id='scan-time', type='number', value=10),\n",
    "    html.Button('Сканировать', id='scan-button'),\n",
    "    html.Div(id='output-table')\n",
    "])\n",
    "\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('output-table', 'children'),\n",
    "    [dash.dependencies.Input('scan-button', 'n_clicks')],\n",
    "    [dash.dependencies.State('start-range', 'value'),\n",
    "     dash.dependencies.State('end-range', 'value'),\n",
    "     dash.dependencies.State('scan-time', 'value')])\n",
    "async def scan_devices(n_clicks, start_range, end_range, scan_time):\n",
    "    device_names = [\"TD_\" + str(i) for i in range(start_range, end_range+1)]\n",
    "    devices = {name: {'name': name, 'address': None, 'rssi': None, 'uuids': None} for name in device_names}\n",
    "    table = html.Table([\n",
    "        html.Thead(html.Tr([html.Th('Name'), html.Th('Address'), html.Th('RSSI'), html.Th('UUIDs')])),\n",
    "        html.Tbody([html.Tr([\n",
    "            html.Td(devices[name]['name']),\n",
    "            html.Td(devices[name]['address']),\n",
    "            html.Td(devices[name]['rssi']),\n",
    "            html.Td(devices[name]['uuids'])\n",
    "        ], style={'color': 'red'}) for name in devices])\n",
    "    ])\n",
    "    for i in range(scan_time):\n",
    "        devices_found = await BleakScanner.discover()\n",
    "        for d in devices_found:\n",
    "            if d.name in devices:\n",
    "                devices[d.name]['address'] = d.address\n",
    "                devices[d.name]['rssi'] = d.rssi\n",
    "                devices[d.name]['uuids'] = d.metadata['uuids']\n",
    "                table.children[1].children[device_names.index(d.name)].style = {'color': 'green'}\n",
    "    return table\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b12302bf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
